#!/usr/bin/env python

import argparse
import ow, OwConfig, OwLib

parser = argparse.ArgumentParser(description="Locates devices in OwConfig.sensor_list on a list of servers.")

parser.add_argument("-d", "--debug",
                  dest="debug", default=0, action="count",
                  help="Increase the debug level")

parser.add_argument("servers", default=["localhost:4304"],
                  nargs="+",
                  help="Specify address for owservers to scan. Default is %(default)s")

args = parser.parse_args()

OwConfig.debug = args.debug
OwLib.debug = args.debug

for server in args.servers:
    ow.init(server)
    print "Scanning", server
    all_sensors = OwLib.find_all_sensors()
    OwConfig.init_sensor_list(server, all_sensors)
    ow.finish();

for s,c in OwConfig.sensor_list.iteritems():
    if 'sensor' in c.keys():
        print "{:4s} {:15s} {:12s} {}".format(c['label'], s, c['server'], c['sensor'])
