#! /usr/bin/env python

import sys
import argparse
import ow


def tree( sensor ):
    print '%7s - %s' % ( sensor._type, sensor._path )
    for next in sensor.sensors( ):
        if next._type in [ 'DS2409', ]:
            tree( next )
        else:
            print '%7s - %s' % ( next._type, next._path )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Lists all devices found on the indicated owserver")
    parser.add_argument("-d", "--debug",
                      dest="debug", default=0, action="count",
                      help="Increase the debug level")
    parser.add_argument("-s", "--server", default="localhost:4304",
                      dest="server", action="store",
                      help="Specify owserver address. Default is %(default)s")
    args = parser.parse_args()

    if args.debug:
        print "Connecting to: %s" % args.server

    # initialize the interface and set the desired units.
    ow.init(args.server)

    root = ow.Sensor('/')
    tree( root )
