#! /usr/bin/env python

import sys
import ow


def tree( sensor ):
    print '%7s - %s' % ( sensor._type, sensor._path )
    for next in sensor.sensors( ):
        if next._type in [ 'DS2409', ]:
            tree( next )
        else:
            print '%7s - %s' % ( next._type, next._path )


if __name__ == "__main__":
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option("-d", "--debug",
                      dest="debug", default=0, action="count",
                      help="Increase the debug level")
    parser.add_option("-s", "--server", default="localhost:4304",
                      dest="server", action="store",
                      help="Specify owserver address")
    (options, args) = parser.parse_args()

    if options.debug:
        print "debug: %d" % options.debug
        print "Connecting to: %s" % options.server

    # initialize the interface and set the desired units.
    ow.init(options.server)

    root = ow.Sensor('/')
    tree( root )
